import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalContextProvider from "@/context/global";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import ThemeContextProvider from "@/context/theme";
import ThemeWrapper from "@/components/ThemeWrapper";
import ChatContextProvider from "@/context/chat";
// import { useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeContextProvider>
        <GlobalContextProvider>
        <ChatContextProvider>
          <ThemeWrapper>

            <Navbar/>

            {children}
          </ThemeWrapper>
          <Toaster />

        </ChatContextProvider>
        </GlobalContextProvider>
        </ThemeContextProvider>

      </body>
    </html>
  );
}
